parameters:
    codefog_bootstrap.template_mapper:
        # Forms
        form_checkbox: cfgbs_form_checkbox
        form_radio: cfgbs_form_radio
        form_select: cfgbs_form_select
        form_submit: cfgbs_form_submit
        form_textarea: cfgbs_form_textarea
        form_textfield: cfgbs_form_textfield

        # Frontend pages
        fe_page: cfgbs_fe_page

        # Modules
        mod_breadcrumb: cfgbs_mod_breadcrumb
        mod_search: cfgbs_mod_search

        # Pagination
        pagination: cfgbs_pagination